---
version: "3"
networks:
  dbt-network:

services:
  postgres:
    image: postgres${POSTGRES_VERSION_TAG}
    container_name: postgres
    restart: always
    networks:
      - dbt-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3" 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/2-data.sql
      - ./postgres/date.sql:/docker-entrypoint-initdb.d/3-date.sql
  pgadmin:
    depends_on:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - dbt-network
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
  dbt-postgres:
    depends_on:
      - postgres
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: dbt-postgres
    networks:
      - dbt-network
    ports:
      - "8085:8085"
    command: ["./wait-for-it.sh", "postgres:5432", "--", "dbt", "debug"]

