
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_postgres_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt-postgres'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "logs"

vars:
  start_date: '2005-01-01'
  high_date: '9999-12-31'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_postgres_demo:
      materialized: table
      staging:
        schema: staging
        materialized: view
      marts:
        dim:
          schema: dim
          materialized: table
        fact:
          schema: fact
          materialized: table
      presentation:
        schema: analytics
        materialized: view

seeds:
  dbt_postgres_demo:
    schema: raw # all seeds in this project will use the mapping schema by default
    imdb:
      schema: imdb # seeds in the `data/imdb/ subdirectory will use the imdb schema
    sakila:
      schema: sakila # seeds in the `data/sakila/ subdirectory will use the sakila schema
      address:
        +column_types:
          phone: varchar(50)
    lookups:
      schema: lookups # seeds in the `data/lookups/ subdirectory will use the lookups schema